### ISSUE TITLE
Cannot import `larch.util.excel`

### ISSUE THREAD

**Issue by mattwigway** [driftlesslabs/larch#1]
When I `import larch.util.excel`, which is used in the activitysim estimation examples, I get the following message (I believe the OMP warning is unrelated):

```
OMP: Info #276: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mwbc/miniforge3/envs/asim/lib/python3.11/site-packages/larch/util/excel.py", line 15, in <module>
    from ..jaxmodel.model_group import ModelGroup
ModuleNotFoundError: No module named 'larch.jaxmodel'
```

`larch` 6.0.22, conda-forge Python 3.11.9, macOS arm64.

**Comment by jpn--** [comment]
This should also be fixed now.  Thanks!
